# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build greetings package
      run: |
        cd /home/runner/work/GoHelloWorld/GoHelloWorld/greetings
        go build -v

    - name: Test greetings package
      run: |
        cd /home/runner/work/GoHelloWorld/GoHelloWorld/greetings
        go test -v

    - name: Build helloworld package
      run: |
        cd /home/runner/work/GoHelloWorld/GoHelloWorld/helloworld
        go build -v

    - name: Test helloworld package
      run: |
        cd /home/runner/work/GoHelloWorld/GoHelloWorld/helloworld
        go test -v

    - name: Build heolovebanhbaogo
      run: go build -v
